Chnages in Azure Pipeline

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -26,12 +26,42 @@ stages:
       displayName: 'Install and select Go Version $(GOVERSION)'
 
     - script:
-          $go get -u github.com/jstemmer/go-junit-report 2>&1
-          $go get -u github.com/axw/gocov/gocov 2>&1
-          $go get -u github.com/AlekSi/gocov-xml 2>&1
+          go get -u github.com/jstemmer/go-junit-report 2>&1
+          go get -u github.com/axw/gocov/gocov 2>&1
+          go get -u github.com/AlekSi/gocov-xml 2>&1
 
+        go test ./serviantestapp -v -coverprofile=demo-coverage.txt -covermode count 2>&1 | $HOME/go/bin/go-junit-report 
+        rc=${PIPESTATUS[0]}
+        $HOME/go/bin/gocov convert demo-coverage.txt > demo-coverage.json
+        $HOME/go/bin/gocov-xml < demo-coverage.json > demo-coverage.xml
+
+        if [ rc -ne 0]; then
+          >&2 echo "Tests Failed"
+        fi
+      displayName: 'Run Unit tests and convert results'
+      failonStderr: true
     - task: $Go@0
       inputs:
         command: 'build'
         arguments: '-a -o serviantestchallenge'
       displayName: 'Build Go App'
+    - publish: '$(Build.Source.Directory)/demo'
+      artifact: 'Executable'
+      displayName: 'Publish Pipeline Artifact'
+
+    - task: PublishTestResults@2
+      condition: always()
+      inputs:
+        testResultsFormat: 'JUnit'
+        testResultsFile: '*report*.xml'
+        searchFolder: '$(Build.SourceDirectory)'
+      displayName: 'Publish Test Results'
+
+      - task: PublishCodeCoverageResults@1
+        condition: always()
+        inputs:
+          codeCoverageTool: 'Cobertura'
+          summaryFileLocation: '$(Build.SourceDirectory)/demo-coverage.xml'
+          displayName: 'Publish Code Coverage Results'
+
+          
